@echo off
setlocal
set PEERADDRBASE=7055
set EVENTSRVBASE=7053
set FILEPATHBASE=%appdata%\hyperledger01

set /a ADDRPORT=%PEERADDRBASE%+%1*100
set /a EVENTPORT=%EVENTSRVBASE%+%1*100
set CORE_PEER_LISTENADDRESS=127.0.0.1:%ADDRPORT%
set CORE_PEER_ADDRESS=%CORE_PEER_LISTENADDRESS%
set CORE_PEER_VALIDATOR_EVENTS_ADDRESS=127.0.0.1:%EVENTPORT%
set CORE_PEER_ID=billgates_%1
set CORE_PEER_FILESYSTEMPATH=%FILEPATHBASE%\sync%1
set CORE_SYNC_TEST_SERVER=false
start cmd /k sync.exe
rem start echo .
endlocal